# Generated by Django 6.1.1 on 2026-09-30 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_projectpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='status',
        ),
        migrations.AddField(
            model_name='projectpost',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='공개 여부'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='권한 부여일')),
                ('granted_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='granted_project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='권한 부여자')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='blog.project', verbose_name='프로젝트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '프로젝트 멤버',
                'verbose_name_plural': '프로젝트 멤버',
                'ordering': ['project', 'user'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='managed_projects', through='blog.ProjectMember', through_fields=('project', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='관리 멤버'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_member'),
        ),
    ]
