# Generated by Django 6.1.1 on 2026-10-01 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_projectpost_status_projectpost_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('message', models.TextField(max_length=2000, verbose_name='문의 내용')),
                ('status', models.CharField(choices=[('new', '새 문의'), ('in_progress', '확인 중'), ('replied', '답변 완료')], db_index=True, default='new', max_length=20, verbose_name='상태')),
                ('reply', models.TextField(blank=True, max_length=5000, verbose_name='답변 내용')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='메일 발송일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접수일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('replied_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='답변자')),
            ],
            options={
                'verbose_name': '문의',
                'verbose_name_plural': '문의',
                'ordering': ['-created_at'],
            },
        ),
    ]
